package contextmenu

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"

	"github.com/sundeiii/yeet-client/internal/i18n"
)

const ownershipMarker = "Generated by yeet-client"

// menuLabel is the entry's name in the app's language. Applying the menu
// again after a language change renames it.
func menuLabel() string {
	return i18n.T("Upload with puush")
}

// allMenuLabels are the entry's names in every language, so an entry made
// in another language can be found and removed (on Linux and macOS the
// name is part of the file name).
func allMenuLabels() []string {
	seen := map[string]bool{}
	var labels []string
	for _, language := range i18n.Languages {
		label := i18n.In(language.Code, "Upload with puush")
		if !seen[label] {
			seen[label] = true
			labels = append(labels, label)
		}
	}
	return labels
}

var (
	ErrDevelopmentBuild    = errors.New("context menus are not supported for temporary development builds")
	ErrUnsupportedPlatform = errors.New("context menus are not supported on this platform")
)

// Apply installs / removes the context menu integration for the current user.
func Apply(enabled bool) error {
	executable, err := os.Executable()
	if err != nil {
		return fmt.Errorf("find puush executable: %w", err)
	}
	executable, err = filepath.Abs(executable)
	if err != nil {
		return fmt.Errorf("resolve puush executable: %w", err)
	}
	return applyPlatform(filepath.Clean(executable), enabled)
}
