package contextmenu

import (
	"bytes"
	"embed"
	"encoding/xml"
	"fmt"
	"path"
	"strings"
	"text/template"
)

//go:embed templates/*
var contextMenuTemplates embed.FS

type contextMenuTemplateData struct {
	Command         string
	DesktopCommand  string // "puush -upload %F"
	Executable      string // "/path/to/puush"
	IconPath        string // "/path/to/puush.png"
	MarkerEnd       string // "<!-- Generated by puush End. -->"
	MarkerStart     string // "<!-- Generated by puush Start. -->"
	MenuLabel       string // "Upload to puush"
	OwnershipMarker string // "Generated by puush"
}

func newContextMenuTemplateData(executable string, iconPath string) contextMenuTemplateData {
	return contextMenuTemplateData{
		DesktopCommand:  desktopEntryQuote(executable) + " -upload %F",
		Executable:      executable,
		IconPath:        iconPath,
		MenuLabel:       menuLabel,
		OwnershipMarker: ownershipMarker,
		MarkerEnd:       "<!-- " + ownershipMarker + " End. -->",
		MarkerStart:     "<!-- " + ownershipMarker + " Start. -->",
	}
}

func renderContextMenuTemplate(name string, data contextMenuTemplateData) ([]byte, error) {
	templatePath := path.Join("templates", name)
	templateName := path.Base(name)
	tmpl, err := template.New(templateName).Funcs(template.FuncMap{
		"desktopEntryQuote": desktopEntryQuote,
		"shellQuote":        shellQuote,
		"xmlEscape":         escapeXML,
	}).ParseFS(contextMenuTemplates, templatePath)
	if err != nil {
		return nil, fmt.Errorf("parse context-menu template %s: %w", name, err)
	}

	var rendered bytes.Buffer
	if err := tmpl.ExecuteTemplate(&rendered, templateName, data); err != nil {
		return nil, fmt.Errorf("render context-menu template %s: %w", name, err)
	}
	return rendered.Bytes(), nil
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'"'"'`) + "'"
}

func desktopEntryQuote(value string) string {
	replacer := strings.NewReplacer(
		`\`, `\\`,
		`"`, `\"`,
		"`", "\\`",
		`$`, `\$`,
		`%`, `%%`,
	)
	return `"` + replacer.Replace(value) + `"`
}

func escapeXML(value string) (string, error) {
	var escaped bytes.Buffer
	if err := xml.EscapeText(&escaped, []byte(value)); err != nil {
		return "", err
	}
	return escaped.String(), nil
}
